[features]
seeds = false
skip-lint = false
[programs.localnet]
wsos_wk03 = "CiuFWGhGHgGm2LS6csbQmfEsxaSTLxHNL9Fh6D6eriTQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/pk/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
